// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdDSHmEj60G_Ar3rVG2jVZ3s5gesmuRdk',
    appId: '1:746357564951:web:1e548bfe5a82d3d071de52',
    messagingSenderId: '746357564951',
    projectId: 'movies-app-933b5',
    authDomain: 'movies-app-933b5.firebaseapp.com',
    storageBucket: 'movies-app-933b5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDetZCLy8Z9fSTiPnt9nnoUjurCTpQlvLA',
    appId: '1:746357564951:android:5fe97ecd9ab0ebe671de52',
    messagingSenderId: '746357564951',
    projectId: 'movies-app-933b5',
    storageBucket: 'movies-app-933b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkUK-RwnZY-fY1AjNmXzMq1EjTRjz2Urc',
    appId: '1:746357564951:ios:07ab4f39ab1045d671de52',
    messagingSenderId: '746357564951',
    projectId: 'movies-app-933b5',
    storageBucket: 'movies-app-933b5.appspot.com',
    iosClientId: '746357564951-ftdckaep2ipojn3bhvlu37dci0itb791.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkUK-RwnZY-fY1AjNmXzMq1EjTRjz2Urc',
    appId: '1:746357564951:ios:07ab4f39ab1045d671de52',
    messagingSenderId: '746357564951',
    projectId: 'movies-app-933b5',
    storageBucket: 'movies-app-933b5.appspot.com',
    iosClientId: '746357564951-ftdckaep2ipojn3bhvlu37dci0itb791.apps.googleusercontent.com',
    iosBundleId: 'com.example.moviesApp',
  );
}
